<div class="row text-center ">
            <div class="col-md-12">
                <br /><br />
                <h2> Iniciar sesión</h2>
               
                <h5>Inicia sesión para tener acceso</h5>
                 <br />
            </div>
        </div>
         <div class="row ">
               
                  <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
                            <?php View::content() ?>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                        <strong>   Ingresa los datos para iniciar sesión</strong>  
                            </div>
                            <div class="panel-body">
                                <?php echo Form::open('','post','role="form"') ?>
                                       <br />
                                     <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-tag"  ></i></span>
                                            <input type="text" name="email" class="form-control" placeholder="Tu email " />
                                        </div>
                                        <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-lock"  ></i></span>
                                            <input type="password" name="clave" class="form-control"  placeholder="Tu Contraseña" />
                                        </div>
                                    <div class="form-group">
                                            <label class="checkbox-inline">
                                                <input type="checkbox" /> Recordarme
                                            </label>
                                            <span class="pull-right">
                                                   <a href="#" >¿Contraseña olvidada? </a> 
                                            </span>
                                        </div>
                                     
                                    <input type="submit" class="btn btn-primary " value="Iniciar sesión ahora">
                                    <hr />
                                    ¿ No está registrado ? <a href="<?php print PUBLIC_PATH.'index/register' ?>" >haga clic aquí </a> 
                                    </form>
                            </div>
                           
                        </div>
                    </div>
                
                
        </div>