<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Central File Web
  <?php if (isset($title)): ?>
    <?php echo ' | '.$title ?>
  <?php endif ?>
  </title>
  <?php Tag::css('bienvenida') ?>
  <?php Tag::css('style') ?>
    <link href="<?php print PUBLIC_PATH ?>assets/css/bootstrap.css" rel="stylesheet" />
     <!-- FONTAWESOME STYLES-->
    <link href="<?php print PUBLIC_PATH ?>assets/css/font-awesome.css" rel="stylesheet" />
     <!-- MORRIS CHART STYLES-->
    <link href="<?php print PUBLIC_PATH ?>assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
    <link href="<?php print PUBLIC_PATH ?>assets/css/custom.css" rel="stylesheet" />
     <!-- GOOGLE FONTS-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
  <?php echo Html::includeCss() ?>
    <script src="<?php print PUBLIC_PATH ?>assets/js/jquery-1.10.2.js"></script>
      <!-- BOOTSTRAP SCRIPTS -->
    <script src="<?php print PUBLIC_PATH ?>assets/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="<?php print PUBLIC_PATH ?>assets/js/jquery.metisMenu.js"></script>
     <!-- MORRIS CHART SCRIPTS -->
     <script src="<?php print PUBLIC_PATH ?>assets/js/morris/raphael-2.1.0.min.js"></script>
    <script src="<?php print PUBLIC_PATH ?>assets/js/morris/morris.js"></script>
      <!-- CUSTOM SCRIPTS -->
    <!-- <script src="<?php print PUBLIC_PATH ?>assets/js/custom.js"></script> -->
</head>
<body>
  <div class="container">
    <?php View::content(); ?>
  </div>
</body>
</html>
